name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - awscli==1.22.23
  - boto3==1.20.23
  - dash==2.0.0
  - fsspec==2021.11.1
  - imbalanced-learn==0.8.1
  - ipykernel==6.6.0
  - jupyter-dash==0.4.0
  - matplotlib==3.5.0
  - numpy==1.21.1
  - openpyxl==3.0.9
  - pandas==1.3.1
  - pip==21.3.1
  - plotly==5.4.0
  - python==3.9.6
  - python-dateutil==2.8.2
  - s3fs==0.4.2
  - scikit-learn==1.0.1
  - scikit-optimize==0.9.0
  - seaborn==0.11.2
  - snowflake-connector-python[pandas]==2.7.0
  - tensorflow==2.4.1
  - pip:
    - sagemaker==2.7.0