
name: base
channels:
  - conda-forge
dependencies:
  - awscli==1.22.15
  - boto3==1.20.15
  - ipykernel==6.5.1
  - matplotlib==3.5.0
  - numpy==1.21.4
  - pandas==1.3.4
  - pip==21.3.1
  - python==3.7.12
  - scikit-learn==1.0.1
  - scikit-optimize==0.9.0
  - seaborn==0.11.2
  - tensorflow==2.4.1